name: Model Architecture Checks

on: [push, pull_request]

jobs:
  model-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.0.1+cpu torchvision==0.15.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install tqdm pytest
        
    - name: Run model checks
      run: |
        pytest tests/test_model.py -v